development:
  adapter: asy.nc

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://vueqydslcrdhta:2FXiVuHNuMwUHV7GMFkBTNhfU0@ec2-54-163-248-14.compute-1.amazonaws.com:5432/d4u1ri4po5jotq
